version: '3'
networks:
  go_delay_network:

services:
  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - 11300:11300
    volumes:
      - ./beanstalk_data:/data
    networks:
      - go_delay_network
  beanstalkd-console:
    image: schickling/beanstalkd-console
    container_name: beanstalkd-console
    depends_on:
      - beanstalkd
    links:
      - beanstalkd
    environment:
      BEANSTALKD_PORT_11300_TCP_ADDR: beanstalkd
    ports:
      - 2080:2080
    networks:
      - go_delay_network
